In [2]:
import torch
import numpy as np

In [3]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5,6],
    [7,8]
], dtype=torch.float32)

In [4]:
t1 + t2

tensor([[ 6.,  8.],
        [10., 12.]])

In [13]:
t1 * t2

tensor([[ 5., 12.],
        [21., 32.]])

In [14]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [15]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [16]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [17]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])